/* soapC.c
   Generated by gSOAP 2.8.133 for conecta4.h

gSOAP XML Web services tools
Copyright (C) 2000-2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif

#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapC.c ver 2.8.133 2024-10-24 14:52:12 GMT")


#ifndef WITH_NOGLOBAL

SOAP_FMAC3 int SOAP_FMAC4 soap_getheader(struct soap *soap)
{
	soap->part = SOAP_IN_HEADER;
	soap->header = soap_in_SOAP_ENV__Header(soap, "SOAP-ENV:Header", soap->header, NULL);
	soap->part = SOAP_END_HEADER;
	return soap->header == NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_putheader(struct soap *soap)
{
	if (soap->version && soap->header)
	{	soap->part = SOAP_IN_HEADER;
		if (soap_out_SOAP_ENV__Header(soap, "SOAP-ENV:Header", 0, soap->header, ""))
			return soap->error;
		soap->part = SOAP_END_HEADER;
	}
	return SOAP_OK;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serializeheader(struct soap *soap)
{
	if (soap->version && soap->header)
		soap_serialize_SOAP_ENV__Header(soap, soap->header);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_header(struct soap *soap)
{
	if (soap->header == NULL)
	{	if ((soap->header = (struct SOAP_ENV__Header*)soap_malloc(soap, sizeof(struct SOAP_ENV__Header))))
			soap_default_SOAP_ENV__Header(soap, soap->header);
	}
}

SOAP_FMAC3 void SOAP_FMAC4 soap_fault(struct soap *soap)
{
	if (soap->fault == NULL)
	{	soap->fault = soap_new_SOAP_ENV__Fault(soap, -1);
		if (soap->fault == NULL)
			return;
	}
	if (soap->version == 2 && soap->fault->SOAP_ENV__Code == NULL)
		soap->fault->SOAP_ENV__Code = soap_new_SOAP_ENV__Code(soap, -1);
	if (soap->version == 2 && soap->fault->SOAP_ENV__Reason == NULL)
		soap->fault->SOAP_ENV__Reason = soap_new_SOAP_ENV__Reason(soap, -1);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serializefault(struct soap *soap)
{
	if (soap->fault)
		soap_serialize_SOAP_ENV__Fault(soap, soap->fault);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_putfault(struct soap *soap)
{
	if (soap->fault)
		return soap_put_SOAP_ENV__Fault(soap, soap->fault, "SOAP-ENV:Fault", "");
	return SOAP_OK;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_getfault(struct soap *soap)
{
	return (soap->fault = soap_get_SOAP_ENV__Fault(soap, NULL, "SOAP-ENV:Fault", NULL)) == NULL;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->fault == NULL)
		return NULL;
	if (soap->version == 2 && soap->fault->SOAP_ENV__Code)
		return (const char**)(void*)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Value;
	return (const char**)(void*)&soap->fault->faultcode;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultsubcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->fault == NULL)
		return NULL;
	if (soap->version == 2 && soap->fault->SOAP_ENV__Code)
	{	if (soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode == NULL)
		{	soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode = soap_new_SOAP_ENV__Code(soap, -1);
			if (soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode == NULL)
				return NULL;
		}
		return (const char**)(void*)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode->SOAP_ENV__Value;
	}
	return (const char**)(void*)&soap->fault->faultcode;
}

SOAP_FMAC3 const char * SOAP_FMAC4 soap_fault_subcode(struct soap *soap)
{
	if (!soap->fault)
		return NULL;
	if (soap->version == 2)
		return soap->fault->SOAP_ENV__Code && soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode ? soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode->SOAP_ENV__Value : NULL;
	return soap->fault->faultcode;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultstring(struct soap *soap)
{
	soap_fault(soap);
	if (soap->fault == NULL)
		return NULL;
	if (soap->version == 2 && soap->fault->SOAP_ENV__Reason)
		return (const char**)(void*)&soap->fault->SOAP_ENV__Reason->SOAP_ENV__Text;
	return (const char**)(void*)&soap->fault->faultstring;
}

SOAP_FMAC3 const char * SOAP_FMAC4 soap_fault_string(struct soap *soap)
{
	const char **s = soap_faultstring(soap);
	return s ? *s : NULL;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultdetail(struct soap *soap)
{
	soap_fault(soap);
	if (soap->fault == NULL)
		return NULL;
	if (soap->version == 2)
	{	if (soap->fault->SOAP_ENV__Detail == NULL)
			soap->fault->SOAP_ENV__Detail = soap_new_SOAP_ENV__Detail(soap, -1);
		return (const char**)(void*)&soap->fault->SOAP_ENV__Detail->__any;
	}
	if (soap->fault->detail == NULL)
		soap->fault->detail = soap_new_SOAP_ENV__Detail(soap, -1);
	return (const char**)(void*)&soap->fault->detail->__any;
}

SOAP_FMAC3 const char * SOAP_FMAC4 soap_fault_detail(struct soap *soap)
{
	const char **s = soap_faultdetail(soap);
	return s ? *s : NULL;
}

#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap *soap)
{
	int t;
	if (soap->version == 1)
	{	for (;;)
		{	if (!soap_getelement(soap, NULL, &t))
				if ((soap->error && soap->error != SOAP_TAG_MISMATCH) || soap_ignore_element(soap))
					break;
		}
	}
	if (soap->error == SOAP_NO_TAG || soap->error == SOAP_EOF)
		soap->error = SOAP_OK;
	return soap->error;
}
#endif
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap *soap, const char *tag, int *type)
{	(void)type;
	if (soap_peek_element(soap))
		return NULL;
#ifndef WITH_NOIDREF
	if (!*soap->id || !(*type = soap_lookup_type(soap, soap->id)))
		*type = soap_lookup_type(soap, soap->href);
	switch (*type)
	{
	case SOAP_TYPE_byte:
		return soap_in_byte(soap, tag, NULL, "xsd:byte");
	case SOAP_TYPE_int:
		return soap_in_int(soap, tag, NULL, "xsd:int");
	case SOAP_TYPE_conecta4ns__tMove:
		return soap_in_conecta4ns__tMove(soap, tag, NULL, "conecta4ns:tMove");
	case SOAP_TYPE_moves:
		return soap_in_moves(soap, tag, NULL, "moves");
	case SOAP_TYPE_conecta4ns__tPlayer:
		return soap_in_conecta4ns__tPlayer(soap, tag, NULL, "conecta4ns:tPlayer");
	case SOAP_TYPE_players:
		return soap_in_players(soap, tag, NULL, "players");
	case SOAP_TYPE_conecta4ns__getStatus:
		return soap_in_conecta4ns__getStatus(soap, tag, NULL, "conecta4ns:getStatus");
	case SOAP_TYPE_conecta4ns__getStatusResponse:
		return soap_in_conecta4ns__getStatusResponse(soap, tag, NULL, "conecta4ns:getStatusResponse");
	case SOAP_TYPE_conecta4ns__register:
		return soap_in_conecta4ns__register(soap, tag, NULL, "conecta4ns:register");
	case SOAP_TYPE_conecta4ns__registerResponse:
		return soap_in_conecta4ns__registerResponse(soap, tag, NULL, "conecta4ns:registerResponse");
	case SOAP_TYPE_conecta4ns__tBlock:
		return soap_in_conecta4ns__tBlock(soap, tag, NULL, "conecta4ns:tBlock");
	case SOAP_TYPE_tBlock:
		return soap_in_tBlock(soap, tag, NULL, "tBlock");
	case SOAP_TYPE_conecta4ns__tMessage:
		return soap_in_conecta4ns__tMessage(soap, tag, NULL, "conecta4ns:tMessage");
	case SOAP_TYPE_tMessage:
		return soap_in_tMessage(soap, tag, NULL, "tMessage");
	case SOAP_TYPE_PointerToconecta4ns__tBlock:
		return soap_in_PointerToconecta4ns__tBlock(soap, tag, NULL, "conecta4ns:tBlock");
	case SOAP_TYPE_PointerToint:
		return soap_in_PointerToint(soap, tag, NULL, "xsd:int");
	case SOAP_TYPE_xsd__string:
	{	char **s;
		s = soap_in_xsd__string(soap, tag, NULL, "xsd:string");
		return s ? *s : NULL;
	}
	case SOAP_TYPE__QName:
	{	char **s;
		s = soap_in__QName(soap, tag, NULL, "xsd:QName");
		return s ? *s : NULL;
	}
	case SOAP_TYPE_string:
	{	char **s;
		s = soap_in_string(soap, tag, NULL, "xsd:string");
		return s ? *s : NULL;
	}
	default:
#else
	*type = 0;
#endif
	{	const char *t = soap->type;
		if (!*t)
			t = soap->tag;
		if (!soap_match_tag(soap, t, "xsd:byte"))
		{	*type = SOAP_TYPE_byte;
			return soap_in_byte(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:int"))
		{	*type = SOAP_TYPE_int;
			return soap_in_int(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:tMove"))
		{	*type = SOAP_TYPE_conecta4ns__tMove;
			return soap_in_conecta4ns__tMove(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "moves"))
		{	*type = SOAP_TYPE_moves;
			return soap_in_moves(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:tPlayer"))
		{	*type = SOAP_TYPE_conecta4ns__tPlayer;
			return soap_in_conecta4ns__tPlayer(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "players"))
		{	*type = SOAP_TYPE_players;
			return soap_in_players(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:getStatus"))
		{	*type = SOAP_TYPE_conecta4ns__getStatus;
			return soap_in_conecta4ns__getStatus(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:getStatusResponse"))
		{	*type = SOAP_TYPE_conecta4ns__getStatusResponse;
			return soap_in_conecta4ns__getStatusResponse(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:register"))
		{	*type = SOAP_TYPE_conecta4ns__register;
			return soap_in_conecta4ns__register(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:registerResponse"))
		{	*type = SOAP_TYPE_conecta4ns__registerResponse;
			return soap_in_conecta4ns__registerResponse(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:tBlock"))
		{	*type = SOAP_TYPE_conecta4ns__tBlock;
			return soap_in_conecta4ns__tBlock(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "tBlock"))
		{	*type = SOAP_TYPE_tBlock;
			return soap_in_tBlock(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "conecta4ns:tMessage"))
		{	*type = SOAP_TYPE_conecta4ns__tMessage;
			return soap_in_conecta4ns__tMessage(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "tMessage"))
		{	*type = SOAP_TYPE_tMessage;
			return soap_in_tMessage(soap, tag, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:string"))
		{	char **s;
			*type = SOAP_TYPE_xsd__string;
			s = soap_in_xsd__string(soap, tag, NULL, NULL);
			return s ? *s : NULL;
		}
		if (!soap_match_tag(soap, t, "xsd:QName"))
		{	char **s;
			*type = SOAP_TYPE__QName;
			s = soap_in__QName(soap, tag, NULL, NULL);
			return s ? *s : NULL;
		}
		if (!soap_match_tag(soap, t, "xsd:string"))
		{	char **s;
			*type = SOAP_TYPE_string;
			s = soap_in_string(soap, tag, NULL, NULL);
			return s ? *s : NULL;
		}
		t = soap->tag;
#ifndef WITH_NOIDREF
	}
#endif
	}
	soap->error = SOAP_TAG_MISMATCH;
	return NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap *soap)
{
	if (!soap_peek_element(soap))
	{	int t;
		DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Unexpected element '%s' in input at level = %u body = %d)\n", soap->tag, soap->level, soap->body));
		if (soap->mustUnderstand && !soap->other && !soap->fignore)
			return soap->error = SOAP_MUSTUNDERSTAND;
		if (((soap->mode & SOAP_XML_STRICT) && !soap->fignore && soap->part != SOAP_IN_HEADER) || !soap_match_tag(soap, soap->tag, "SOAP-ENV:"))
		{	DBGLOG(TEST, SOAP_MESSAGE(fdebug, "REJECTING element '%s'\n", soap->tag));
			return soap->error = SOAP_TAG_MISMATCH;
		}
		if (!*soap->id || !soap_getelement(soap, NULL, &t))
		{	soap->peeked = 0;
			if (soap->fignore)
				soap->error = soap->fignore(soap, soap->tag);
			else
				soap->error = SOAP_OK;
			DBGLOG(TEST, if (!soap->error) SOAP_MESSAGE(fdebug, "IGNORING element '%s'\n", soap->tag));
			if (!soap->error && soap->body && soap_ignore(soap))
				return soap->error;
		}
	}
	return soap->error;
}

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap *soap)
{
	int i;
	struct soap_plist *pp;
	if (soap->version == 1 && soap->encodingStyle && !(soap->mode & (SOAP_XML_TREE | SOAP_XML_GRAPH)))
		for (i = 0; i < SOAP_PTRHASH; i++)
			for (pp = soap->pht[i]; pp; pp = pp->next)
				if (pp->mark1 == 2 || pp->mark2 == 2)
					if (soap_putelement(soap, pp->ptr, SOAP_MULTIREFTAG, pp->id, pp->type))
						return soap->error;
	return SOAP_OK;
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap *soap, const void *ptr, const char *tag, int id, int type)
{	(void)tag;
	switch (type)
	{
	case SOAP_TYPE_byte:
		return soap_out_byte(soap, tag, id, (const char *)ptr, "xsd:byte");
	case SOAP_TYPE_int:
		return soap_out_int(soap, tag, id, (const int *)ptr, "xsd:int");
	case SOAP_TYPE_conecta4ns__tMove:
		return soap_out_conecta4ns__tMove(soap, tag, id, (const enum moves *)ptr, "conecta4ns:tMove");
	case SOAP_TYPE_moves:
		return soap_out_moves(soap, tag, id, (const enum moves *)ptr, "moves");
	case SOAP_TYPE_conecta4ns__tPlayer:
		return soap_out_conecta4ns__tPlayer(soap, tag, id, (const enum players *)ptr, "conecta4ns:tPlayer");
	case SOAP_TYPE_players:
		return soap_out_players(soap, tag, id, (const enum players *)ptr, "players");
	case SOAP_TYPE_conecta4ns__getStatus:
		return soap_out_conecta4ns__getStatus(soap, tag, id, (const struct conecta4ns__getStatus *)ptr, "conecta4ns:getStatus");
	case SOAP_TYPE_conecta4ns__getStatusResponse:
		return soap_out_conecta4ns__getStatusResponse(soap, tag, id, (const struct conecta4ns__getStatusResponse *)ptr, "conecta4ns:getStatusResponse");
	case SOAP_TYPE_conecta4ns__register:
		return soap_out_conecta4ns__register(soap, tag, id, (const struct conecta4ns__register *)ptr, "conecta4ns:register");
	case SOAP_TYPE_conecta4ns__registerResponse:
		return soap_out_conecta4ns__registerResponse(soap, tag, id, (const struct conecta4ns__registerResponse *)ptr, "conecta4ns:registerResponse");
	case SOAP_TYPE_conecta4ns__tBlock:
		return soap_out_conecta4ns__tBlock(soap, tag, id, (const struct tBlock *)ptr, "conecta4ns:tBlock");
	case SOAP_TYPE_tBlock:
		return soap_out_tBlock(soap, tag, id, (const struct tBlock *)ptr, "tBlock");
	case SOAP_TYPE_conecta4ns__tMessage:
		return soap_out_conecta4ns__tMessage(soap, tag, id, (const struct tMessage *)ptr, "conecta4ns:tMessage");
	case SOAP_TYPE_tMessage:
		return soap_out_tMessage(soap, tag, id, (const struct tMessage *)ptr, "tMessage");
	case SOAP_TYPE_PointerToconecta4ns__tBlock:
		return soap_out_PointerToconecta4ns__tBlock(soap, tag, id, (struct tBlock *const*)ptr, "conecta4ns:tBlock");
	case SOAP_TYPE_PointerToint:
		return soap_out_PointerToint(soap, tag, id, (int *const*)ptr, "xsd:int");
	case SOAP_TYPE_xsd__string:
		return soap_out_string(soap, tag, id, (char*const*)(void*)&ptr, "xsd:string");
	case SOAP_TYPE__QName:
		return soap_out_string(soap, tag, id, (char*const*)(void*)&ptr, "xsd:QName");
	case SOAP_TYPE_string:
		return soap_out_string(soap, tag, id, (char*const*)(void*)&ptr, "xsd:string");
	case 0:
		return SOAP_OK;
	}
	DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_putelement '%s' failed for type %d in soapC.c\n", tag ? tag : "", type));
	return soap_element_empty(soap, tag, 0, NULL); /* unknown type to serialize */
}

#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap *soap, const void *ptr, int type)
{
	(void)soap; (void)ptr; (void)type; /* appease -Wall -Werror */
	switch (type)
	{
	case SOAP_TYPE_conecta4ns__getStatus:
		soap_serialize_conecta4ns__getStatus(soap, (const struct conecta4ns__getStatus *)ptr);
		break;
	case SOAP_TYPE_conecta4ns__getStatusResponse:
		soap_serialize_conecta4ns__getStatusResponse(soap, (const struct conecta4ns__getStatusResponse *)ptr);
		break;
	case SOAP_TYPE_conecta4ns__register:
		soap_serialize_conecta4ns__register(soap, (const struct conecta4ns__register *)ptr);
		break;
	case SOAP_TYPE_conecta4ns__registerResponse:
		soap_serialize_conecta4ns__registerResponse(soap, (const struct conecta4ns__registerResponse *)ptr);
		break;
	case SOAP_TYPE_conecta4ns__tBlock:
		soap_serialize_conecta4ns__tBlock(soap, (const struct tBlock *)ptr);
		break;
	case SOAP_TYPE_tBlock:
		soap_serialize_tBlock(soap, (const struct tBlock *)ptr);
		break;
	case SOAP_TYPE_conecta4ns__tMessage:
		soap_serialize_conecta4ns__tMessage(soap, (const struct tMessage *)ptr);
		break;
	case SOAP_TYPE_tMessage:
		soap_serialize_tMessage(soap, (const struct tMessage *)ptr);
		break;
	case SOAP_TYPE_PointerToconecta4ns__tBlock:
		soap_serialize_PointerToconecta4ns__tBlock(soap, (struct tBlock *const*)ptr);
		break;
	case SOAP_TYPE_PointerToint:
		soap_serialize_PointerToint(soap, (int *const*)ptr);
		break;
	case SOAP_TYPE_xsd__string:
		soap_serialize_string(soap, (char*const*)(void*)&ptr);
		break;
	case SOAP_TYPE__QName:
		soap_serialize_string(soap, (char*const*)(void*)&ptr);
		break;
	case SOAP_TYPE_string:
		soap_serialize_string(soap, (char*const*)(void*)&ptr);
		break;
	}
}
#endif

SOAP_FMAC3 void * SOAP_FMAC4 soap_dupelement(struct soap *soap, const void *ptr, int type)
{(void)soap; (void)ptr; (void)type; /* appease -Wall -Werror */
	return NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_delelement(const void *ptr, int type)
{(void)ptr; (void)type; /* appease -Wall -Werror */
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap *soap, const char *tag, int id, const char *a, const char *type)
{
	return soap_outbyte(soap, tag, id, a, type, SOAP_TYPE_byte);
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap *soap, const char *tag, char *a, const char *type)
{
	a = soap_inbyte(soap, tag, a, type, SOAP_TYPE_byte);
	return a;
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_new_byte(struct soap *soap, int n)
{
	char *p;
	char *a = (char*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(char));
	for (p = a; p && n--; p++)
		soap_default_byte(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap *soap, const char *a, const char *tag, const char *type)
{
	if (soap_out_byte(soap, tag ? tag : "byte", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap *soap, char *p, const char *tag, const char *type)
{
	if ((p = soap_in_byte(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap *soap, const char *tag, int id, const int *a, const char *type)
{
	return soap_outint(soap, tag, id, a, type, SOAP_TYPE_int);
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap *soap, const char *tag, int *a, const char *type)
{
	a = soap_inint(soap, tag, a, type, SOAP_TYPE_int);
	return a;
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_new_int(struct soap *soap, int n)
{
	int *p;
	int *a = (int*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(int));
	for (p = a; p && n--; p++)
		soap_default_int(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap *soap, const int *a, const char *tag, const char *type)
{
	if (soap_out_int(soap, tag ? tag : "int", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap *soap, int *p, const char *tag, const char *type)
{
	if ((p = soap_in_int(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__tMove(struct soap *soap, const char *tag, int id, const enum moves *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__tMove), type) || soap_send(soap, soap_conecta4ns__tMove2s(soap, *a)))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 enum moves * SOAP_FMAC4 soap_in_conecta4ns__tMove(struct soap *soap, const char *tag, enum moves *a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type) && soap_match_tag(soap, soap->type, "moves"))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (enum moves*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__tMove, sizeof(enum moves), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	if (*soap->href != '#')
	{	int err = soap_s2conecta4ns__tMove(soap, soap_value(soap), a);
		if ((soap->body && soap_element_end_in(soap, tag)) || err)
			return NULL;
	}
	else
	{	a = (enum moves *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__tMove, SOAP_TYPE_conecta4ns__tMove, sizeof(enum moves), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__tMove(struct soap *soap, const enum moves *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__tMove(soap, tag ? tag : "conecta4ns:tMove", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 enum moves * SOAP_FMAC4 soap_get_conecta4ns__tMove(struct soap *soap, enum moves *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__tMove(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

static const struct soap_code_map soap_codes_moves[] =
{	{ (LONG64)OK_move, "OK-move" },
	{ (LONG64)fullColumn_move, "fullColumn-move" },
	{ 0, NULL }
};

SOAP_FMAC3S const char* SOAP_FMAC4S soap_moves2s(struct soap *soap, enum moves n)
{
	const char *s = soap_code_str(soap_codes_moves, (long)n);
	if (s)
		return s;
	return soap_long2s(soap, (long)n);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_moves(struct soap *soap, const char *tag, int id, const enum moves *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_moves), type) || soap_send(soap, soap_moves2s(soap, *a)))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3S int SOAP_FMAC4S soap_s2moves(struct soap *soap, const char *s, enum moves *a)
{
	const struct soap_code_map *map;
	if (!s)
		return soap->error;
	map = soap_code(soap_codes_moves, s);
	if (map)
		*a = (enum moves)map->code;
	else if (!*s)
		return soap->error = SOAP_EMPTY;
	else
	{	int n;
		if (soap_s2int(soap, s, &n) || n < 0 || n > 1)
			return soap->error = SOAP_TYPE;
		*a = (enum moves)n;
	}
	return SOAP_OK;
}

SOAP_FMAC3 enum moves * SOAP_FMAC4 soap_in_moves(struct soap *soap, const char *tag, enum moves *a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (enum moves*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_moves, sizeof(enum moves), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	if (*soap->href != '#')
	{	int err = soap_s2moves(soap, soap_value(soap), a);
		if ((soap->body && soap_element_end_in(soap, tag)) || err)
			return NULL;
	}
	else
	{	a = (enum moves *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_moves, SOAP_TYPE_moves, sizeof(enum moves), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 enum moves * SOAP_FMAC4 soap_new_moves(struct soap *soap, int n)
{
	enum moves *p;
	enum moves *a = (enum moves*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(enum moves));
	for (p = a; p && n--; p++)
		soap_default_moves(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_moves(struct soap *soap, const enum moves *a, const char *tag, const char *type)
{
	if (soap_out_moves(soap, tag ? tag : "moves", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 enum moves * SOAP_FMAC4 soap_get_moves(struct soap *soap, enum moves *p, const char *tag, const char *type)
{
	if ((p = soap_in_moves(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__tPlayer(struct soap *soap, const char *tag, int id, const enum players *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__tPlayer), type) || soap_send(soap, soap_conecta4ns__tPlayer2s(soap, *a)))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 enum players * SOAP_FMAC4 soap_in_conecta4ns__tPlayer(struct soap *soap, const char *tag, enum players *a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type) && soap_match_tag(soap, soap->type, "players"))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (enum players*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__tPlayer, sizeof(enum players), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	if (*soap->href != '#')
	{	int err = soap_s2conecta4ns__tPlayer(soap, soap_value(soap), a);
		if ((soap->body && soap_element_end_in(soap, tag)) || err)
			return NULL;
	}
	else
	{	a = (enum players *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__tPlayer, SOAP_TYPE_conecta4ns__tPlayer, sizeof(enum players), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__tPlayer(struct soap *soap, const enum players *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__tPlayer(soap, tag ? tag : "conecta4ns:tPlayer", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 enum players * SOAP_FMAC4 soap_get_conecta4ns__tPlayer(struct soap *soap, enum players *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__tPlayer(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

static const struct soap_code_map soap_codes_players[] =
{	{ (LONG64)player1, "player1" },
	{ (LONG64)player2, "player2" },
	{ 0, NULL }
};

SOAP_FMAC3S const char* SOAP_FMAC4S soap_players2s(struct soap *soap, enum players n)
{
	const char *s = soap_code_str(soap_codes_players, (long)n);
	if (s)
		return s;
	return soap_long2s(soap, (long)n);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_players(struct soap *soap, const char *tag, int id, const enum players *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_players), type) || soap_send(soap, soap_players2s(soap, *a)))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3S int SOAP_FMAC4S soap_s2players(struct soap *soap, const char *s, enum players *a)
{
	const struct soap_code_map *map;
	if (!s)
		return soap->error;
	map = soap_code(soap_codes_players, s);
	if (map)
		*a = (enum players)map->code;
	else if (!*s)
		return soap->error = SOAP_EMPTY;
	else
	{	int n;
		if (soap_s2int(soap, s, &n) || n < 0 || n > 1)
			return soap->error = SOAP_TYPE;
		*a = (enum players)n;
	}
	return SOAP_OK;
}

SOAP_FMAC3 enum players * SOAP_FMAC4 soap_in_players(struct soap *soap, const char *tag, enum players *a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (enum players*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_players, sizeof(enum players), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	if (*soap->href != '#')
	{	int err = soap_s2players(soap, soap_value(soap), a);
		if ((soap->body && soap_element_end_in(soap, tag)) || err)
			return NULL;
	}
	else
	{	a = (enum players *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_players, SOAP_TYPE_players, sizeof(enum players), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 enum players * SOAP_FMAC4 soap_new_players(struct soap *soap, int n)
{
	enum players *p;
	enum players *a = (enum players*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(enum players));
	for (p = a; p && n--; p++)
		soap_default_players(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_players(struct soap *soap, const enum players *a, const char *tag, const char *type)
{
	if (soap_out_players(soap, tag ? tag : "players", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 enum players * SOAP_FMAC4 soap_get_players(struct soap *soap, enum players *p, const char *tag, const char *type)
{
	if ((p = soap_in_players(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default__QName(soap, &a->faultcode);
	soap_default_string(soap, &a->faultstring);
	soap_default_string(soap, &a->faultactor);
	a->detail = NULL;
	a->SOAP_ENV__Code = NULL;
	a->SOAP_ENV__Reason = NULL;
	soap_default_string(soap, &a->SOAP_ENV__Node);
	soap_default_string(soap, &a->SOAP_ENV__Role);
	a->SOAP_ENV__Detail = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize__QName(soap, (char*const*)&a->faultcode);
	soap_serialize_string(soap, (char*const*)&a->faultstring);
	soap_serialize_string(soap, (char*const*)&a->faultactor);
	soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->detail);
	soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Code);
	soap_serialize_PointerToSOAP_ENV__Reason(soap, &a->SOAP_ENV__Reason);
	soap_serialize_string(soap, (char*const*)&a->SOAP_ENV__Node);
	soap_serialize_string(soap, (char*const*)&a->SOAP_ENV__Role);
	soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->SOAP_ENV__Detail);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Fault *a, const char *type)
{
	const char *soap_tmp_faultcode;
	soap_tmp_faultcode = soap_QName2s(soap, a->faultcode);
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Fault), type))
		return soap->error;
	if (soap_out__QName(soap, "faultcode", -1, (char*const*)(void*)&soap_tmp_faultcode, ""))
		return soap->error;
	if (soap_out_string(soap, "faultstring", -1, (char*const*)&a->faultstring, ""))
		return soap->error;
	if (soap_out_string(soap, "faultactor", -1, (char*const*)&a->faultactor, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Detail(soap, "detail", -1, &a->detail, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", -1, &a->SOAP_ENV__Code, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", -1, &a->SOAP_ENV__Reason, ""))
		return soap->error;
	if (soap_out_string(soap, "SOAP-ENV:Node", -1, (char*const*)&a->SOAP_ENV__Node, ""))
		return soap->error;
	if (soap_out_string(soap, "SOAP-ENV:Role", -1, (char*const*)&a->SOAP_ENV__Role, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", -1, &a->SOAP_ENV__Detail, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap *soap, const char *tag, struct SOAP_ENV__Fault *a, const char *type)
{
	size_t soap_flag_faultcode = 1;
	size_t soap_flag_faultstring = 1;
	size_t soap_flag_faultactor = 1;
	size_t soap_flag_detail = 1;
	size_t soap_flag_SOAP_ENV__Code = 1;
	size_t soap_flag_SOAP_ENV__Reason = 1;
	size_t soap_flag_SOAP_ENV__Node = 1;
	size_t soap_flag_SOAP_ENV__Role = 1;
	size_t soap_flag_SOAP_ENV__Detail = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct SOAP_ENV__Fault*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Fault(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_faultcode && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in__QName(soap, "faultcode", (char**)&a->faultcode, "xsd:QName"))
				{	soap_flag_faultcode--;
					continue;
				}
			}
			if (soap_flag_faultstring && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in_string(soap, "faultstring", (char**)&a->faultstring, "xsd:string"))
				{	soap_flag_faultstring--;
					continue;
				}
			}
			if (soap_flag_faultactor && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in_string(soap, "faultactor", (char**)&a->faultactor, "xsd:string"))
				{	soap_flag_faultactor--;
					continue;
				}
			}
			if (soap_flag_detail && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToSOAP_ENV__Detail(soap, "detail", &a->detail, ""))
				{	soap_flag_detail--;
					continue;
				}
			}
			if (soap_flag_SOAP_ENV__Code && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", &a->SOAP_ENV__Code, ""))
				{	soap_flag_SOAP_ENV__Code--;
					continue;
				}
			}
			if (soap_flag_SOAP_ENV__Reason && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", &a->SOAP_ENV__Reason, ""))
				{	soap_flag_SOAP_ENV__Reason--;
					continue;
				}
			}
			if (soap_flag_SOAP_ENV__Node && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in_string(soap, "SOAP-ENV:Node", (char**)&a->SOAP_ENV__Node, "xsd:string"))
				{	soap_flag_SOAP_ENV__Node--;
					continue;
				}
			}
			if (soap_flag_SOAP_ENV__Role && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in_string(soap, "SOAP-ENV:Role", (char**)&a->SOAP_ENV__Role, "xsd:string"))
				{	soap_flag_SOAP_ENV__Role--;
					continue;
				}
			}
			if (soap_flag_SOAP_ENV__Detail && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", &a->SOAP_ENV__Detail, ""))
				{	soap_flag_SOAP_ENV__Detail--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Fault *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_new_SOAP_ENV__Fault(struct soap *soap, int n)
{
	struct SOAP_ENV__Fault *p;
	struct SOAP_ENV__Fault *a = (struct SOAP_ENV__Fault*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct SOAP_ENV__Fault));
	for (p = a; p && n--; p++)
		soap_default_SOAP_ENV__Fault(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a, const char *tag, const char *type)
{
	if (soap_out_SOAP_ENV__Fault(soap, tag ? tag : "SOAP-ENV:Fault", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Fault(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->SOAP_ENV__Text);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap *soap, const struct SOAP_ENV__Reason *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize_string(soap, (char*const*)&a->SOAP_ENV__Text);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Reason *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Reason), type))
		return soap->error;
	if (soap->lang)
		soap_set_attr(soap, "xml:lang", soap->lang, 1);
	if (soap_out_string(soap, "SOAP-ENV:Text", -1, (char*const*)&a->SOAP_ENV__Text, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap *soap, const char *tag, struct SOAP_ENV__Reason *a, const char *type)
{
	size_t soap_flag_SOAP_ENV__Text = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct SOAP_ENV__Reason*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Reason(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Text && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in_string(soap, "SOAP-ENV:Text", (char**)&a->SOAP_ENV__Text, "xsd:string"))
				{	soap_flag_SOAP_ENV__Text--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Reason *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Reason, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_new_SOAP_ENV__Reason(struct soap *soap, int n)
{
	struct SOAP_ENV__Reason *p;
	struct SOAP_ENV__Reason *a = (struct SOAP_ENV__Reason*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct SOAP_ENV__Reason));
	for (p = a; p && n--; p++)
		soap_default_SOAP_ENV__Reason(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap *soap, const struct SOAP_ENV__Reason *a, const char *tag, const char *type)
{
	if (soap_out_SOAP_ENV__Reason(soap, tag ? tag : "SOAP-ENV:Reason", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Reason(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__any = NULL;
	a->__type = 0;
	a->fault = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap *soap, const struct SOAP_ENV__Detail *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_markelement(soap, a->fault, a->__type);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Detail *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Detail), type))
		return soap->error;
	if (soap_outliteral(soap, "-any", (char*const*)&a->__any, NULL))
		return soap->error;
	if (soap_putelement(soap, a->fault, "fault", -1, a->__type))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap *soap, const char *tag, struct SOAP_ENV__Detail *a, const char *type)
{
	size_t soap_flag___any = 1;
	size_t soap_flag_fault = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct SOAP_ENV__Detail*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Detail(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_fault && soap->error == SOAP_TAG_MISMATCH)
			{	if ((a->fault = soap_getelement(soap, "fault", &a->__type)))
				{	soap_flag_fault = 0;
					continue;
				}
			}
			if (soap_flag___any && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_inliteral(soap, "-any", (char**)&a->__any))
				{	soap_flag___any--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Detail *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_new_SOAP_ENV__Detail(struct soap *soap, int n)
{
	struct SOAP_ENV__Detail *p;
	struct SOAP_ENV__Detail *a = (struct SOAP_ENV__Detail*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct SOAP_ENV__Detail));
	for (p = a; p && n--; p++)
		soap_default_SOAP_ENV__Detail(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap *soap, const struct SOAP_ENV__Detail *a, const char *tag, const char *type)
{
	if (soap_out_SOAP_ENV__Detail(soap, tag ? tag : "SOAP-ENV:Detail", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Detail(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default__QName(soap, &a->SOAP_ENV__Value);
	a->SOAP_ENV__Subcode = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize__QName(soap, (char*const*)&a->SOAP_ENV__Value);
	soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Subcode);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Code *a, const char *type)
{
	const char *soap_tmp_SOAP_ENV__Value;
	soap_tmp_SOAP_ENV__Value = soap_QName2s(soap, a->SOAP_ENV__Value);
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Code), type))
		return soap->error;
	if (soap_out__QName(soap, "SOAP-ENV:Value", -1, (char*const*)(void*)&soap_tmp_SOAP_ENV__Value, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", -1, &a->SOAP_ENV__Subcode, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code *a, const char *type)
{
	size_t soap_flag_SOAP_ENV__Value = 1;
	size_t soap_flag_SOAP_ENV__Subcode = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct SOAP_ENV__Code*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Code(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Value && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
			{	if (soap_in__QName(soap, "SOAP-ENV:Value", (char**)&a->SOAP_ENV__Value, "xsd:QName"))
				{	soap_flag_SOAP_ENV__Value--;
					continue;
				}
			}
			if (soap_flag_SOAP_ENV__Subcode && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", &a->SOAP_ENV__Subcode, ""))
				{	soap_flag_SOAP_ENV__Subcode--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Code *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_new_SOAP_ENV__Code(struct soap *soap, int n)
{
	struct SOAP_ENV__Code *p;
	struct SOAP_ENV__Code *a = (struct SOAP_ENV__Code*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct SOAP_ENV__Code));
	for (p = a; p && n--; p++)
		soap_default_SOAP_ENV__Code(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a, const char *tag, const char *type)
{
	if (soap_out_SOAP_ENV__Code(soap, tag ? tag : "SOAP-ENV:Code", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Code(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Header *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Header), type))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap *soap, const char *tag, struct SOAP_ENV__Header *a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct SOAP_ENV__Header*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Header(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Header *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Header, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_new_SOAP_ENV__Header(struct soap *soap, int n)
{
	struct SOAP_ENV__Header *p;
	struct SOAP_ENV__Header *a = (struct SOAP_ENV__Header*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct SOAP_ENV__Header));
	for (p = a; p && n--; p++)
		soap_default_SOAP_ENV__Header(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a, const char *tag, const char *type)
{
	if (soap_out_SOAP_ENV__Header(soap, tag ? tag : "SOAP-ENV:Header", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Header(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_default_conecta4ns__getStatus(struct soap *soap, struct conecta4ns__getStatus *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_conecta4ns__tMessage(soap, &a->playerName);
	soap_default_int(soap, &a->gameId);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_conecta4ns__getStatus(struct soap *soap, const struct conecta4ns__getStatus *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize_conecta4ns__tMessage(soap, &a->playerName);
	soap_embedded(soap, &a->gameId, SOAP_TYPE_int);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__getStatus(struct soap *soap, const char *tag, int id, const struct conecta4ns__getStatus *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__getStatus), type))
		return soap->error;
	if (soap_out_conecta4ns__tMessage(soap, "playerName", -1, &a->playerName, ""))
		return soap->error;
	if (soap_out_int(soap, "gameId", -1, &a->gameId, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct conecta4ns__getStatus * SOAP_FMAC4 soap_in_conecta4ns__getStatus(struct soap *soap, const char *tag, struct conecta4ns__getStatus *a, const char *type)
{
	size_t soap_flag_playerName = 1;
	size_t soap_flag_gameId = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct conecta4ns__getStatus*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__getStatus, sizeof(struct conecta4ns__getStatus), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_conecta4ns__getStatus(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_playerName && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_conecta4ns__tMessage(soap, "playerName", &a->playerName, "conecta4ns:tMessage"))
				{	soap_flag_playerName--;
					continue;
				}
			}
			if (soap_flag_gameId && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_int(soap, "gameId", &a->gameId, "xsd:int"))
				{	soap_flag_gameId--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_playerName > 0 || soap_flag_gameId > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
	}
	else if ((soap->mode & SOAP_XML_STRICT) && *soap->href != '#')
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	else
	{	a = (struct conecta4ns__getStatus *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__getStatus, SOAP_TYPE_conecta4ns__getStatus, sizeof(struct conecta4ns__getStatus), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct conecta4ns__getStatus * SOAP_FMAC4 soap_new_conecta4ns__getStatus(struct soap *soap, int n)
{
	struct conecta4ns__getStatus *p;
	struct conecta4ns__getStatus *a = (struct conecta4ns__getStatus*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct conecta4ns__getStatus));
	for (p = a; p && n--; p++)
		soap_default_conecta4ns__getStatus(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__getStatus(struct soap *soap, const struct conecta4ns__getStatus *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__getStatus(soap, tag ? tag : "conecta4ns:getStatus", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct conecta4ns__getStatus * SOAP_FMAC4 soap_get_conecta4ns__getStatus(struct soap *soap, struct conecta4ns__getStatus *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__getStatus(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_conecta4ns__getStatusResponse(struct soap *soap, struct conecta4ns__getStatusResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->status = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_conecta4ns__getStatusResponse(struct soap *soap, const struct conecta4ns__getStatusResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize_PointerToconecta4ns__tBlock(soap, &a->status);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__getStatusResponse(struct soap *soap, const char *tag, int id, const struct conecta4ns__getStatusResponse *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__getStatusResponse), type))
		return soap->error;
	if (soap_out_PointerToconecta4ns__tBlock(soap, "status", -1, &a->status, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct conecta4ns__getStatusResponse * SOAP_FMAC4 soap_in_conecta4ns__getStatusResponse(struct soap *soap, const char *tag, struct conecta4ns__getStatusResponse *a, const char *type)
{
	size_t soap_flag_status = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct conecta4ns__getStatusResponse*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__getStatusResponse, sizeof(struct conecta4ns__getStatusResponse), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_conecta4ns__getStatusResponse(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_status && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToconecta4ns__tBlock(soap, "status", &a->status, "conecta4ns:tBlock"))
				{	soap_flag_status--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct conecta4ns__getStatusResponse *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__getStatusResponse, SOAP_TYPE_conecta4ns__getStatusResponse, sizeof(struct conecta4ns__getStatusResponse), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct conecta4ns__getStatusResponse * SOAP_FMAC4 soap_new_conecta4ns__getStatusResponse(struct soap *soap, int n)
{
	struct conecta4ns__getStatusResponse *p;
	struct conecta4ns__getStatusResponse *a = (struct conecta4ns__getStatusResponse*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct conecta4ns__getStatusResponse));
	for (p = a; p && n--; p++)
		soap_default_conecta4ns__getStatusResponse(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__getStatusResponse(struct soap *soap, const struct conecta4ns__getStatusResponse *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__getStatusResponse(soap, tag ? tag : "conecta4ns:getStatusResponse", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct conecta4ns__getStatusResponse * SOAP_FMAC4 soap_get_conecta4ns__getStatusResponse(struct soap *soap, struct conecta4ns__getStatusResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__getStatusResponse(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_conecta4ns__register(struct soap *soap, struct conecta4ns__register *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_conecta4ns__tMessage(soap, &a->playerName);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_conecta4ns__register(struct soap *soap, const struct conecta4ns__register *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize_conecta4ns__tMessage(soap, &a->playerName);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__register(struct soap *soap, const char *tag, int id, const struct conecta4ns__register *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__register), type))
		return soap->error;
	if (soap_out_conecta4ns__tMessage(soap, "playerName", -1, &a->playerName, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct conecta4ns__register * SOAP_FMAC4 soap_in_conecta4ns__register(struct soap *soap, const char *tag, struct conecta4ns__register *a, const char *type)
{
	size_t soap_flag_playerName = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct conecta4ns__register*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__register, sizeof(struct conecta4ns__register), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_conecta4ns__register(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_playerName && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_conecta4ns__tMessage(soap, "playerName", &a->playerName, "conecta4ns:tMessage"))
				{	soap_flag_playerName--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_playerName > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
	}
	else if ((soap->mode & SOAP_XML_STRICT) && *soap->href != '#')
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	else
	{	a = (struct conecta4ns__register *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__register, SOAP_TYPE_conecta4ns__register, sizeof(struct conecta4ns__register), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct conecta4ns__register * SOAP_FMAC4 soap_new_conecta4ns__register(struct soap *soap, int n)
{
	struct conecta4ns__register *p;
	struct conecta4ns__register *a = (struct conecta4ns__register*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct conecta4ns__register));
	for (p = a; p && n--; p++)
		soap_default_conecta4ns__register(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__register(struct soap *soap, const struct conecta4ns__register *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__register(soap, tag ? tag : "conecta4ns:register", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct conecta4ns__register * SOAP_FMAC4 soap_get_conecta4ns__register(struct soap *soap, struct conecta4ns__register *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__register(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_conecta4ns__registerResponse(struct soap *soap, struct conecta4ns__registerResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->code = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_conecta4ns__registerResponse(struct soap *soap, const struct conecta4ns__registerResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_serialize_PointerToint(soap, &a->code);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__registerResponse(struct soap *soap, const char *tag, int id, const struct conecta4ns__registerResponse *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__registerResponse), type))
		return soap->error;
	if (soap_out_PointerToint(soap, "code", -1, &a->code, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct conecta4ns__registerResponse * SOAP_FMAC4 soap_in_conecta4ns__registerResponse(struct soap *soap, const char *tag, struct conecta4ns__registerResponse *a, const char *type)
{
	size_t soap_flag_code = 1;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct conecta4ns__registerResponse*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__registerResponse, sizeof(struct conecta4ns__registerResponse), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_conecta4ns__registerResponse(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_code && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_PointerToint(soap, "code", &a->code, "xsd:int"))
				{	soap_flag_code--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct conecta4ns__registerResponse *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__registerResponse, SOAP_TYPE_conecta4ns__registerResponse, sizeof(struct conecta4ns__registerResponse), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct conecta4ns__registerResponse * SOAP_FMAC4 soap_new_conecta4ns__registerResponse(struct soap *soap, int n)
{
	struct conecta4ns__registerResponse *p;
	struct conecta4ns__registerResponse *a = (struct conecta4ns__registerResponse*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct conecta4ns__registerResponse));
	for (p = a; p && n--; p++)
		soap_default_conecta4ns__registerResponse(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__registerResponse(struct soap *soap, const struct conecta4ns__registerResponse *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__registerResponse(soap, tag ? tag : "conecta4ns:registerResponse", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct conecta4ns__registerResponse * SOAP_FMAC4 soap_get_conecta4ns__registerResponse(struct soap *soap, struct conecta4ns__registerResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__registerResponse(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_conecta4ns__tBlock(struct soap *soap, struct tBlock *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_int(soap, &a->code);
	soap_default_conecta4ns__tMessage(soap, &a->msgStruct);
	a->__size = 0;
	a->board = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_conecta4ns__tBlock(struct soap *soap, const struct tBlock *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_embedded(soap, &a->code, SOAP_TYPE_int);
	soap_serialize_conecta4ns__tMessage(soap, &a->msgStruct);
	if (a->board)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
		{
			soap_embedded(soap, a->board + i, SOAP_TYPE_byte);
		}
	}
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__tBlock(struct soap *soap, const char *tag, int id, const struct tBlock *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__tBlock), type))
		return soap->error;
	if (soap_out_int(soap, "code", -1, &a->code, ""))
		return soap->error;
	if (soap_out_conecta4ns__tMessage(soap, "msgStruct", -1, &a->msgStruct, ""))
		return soap->error;
	if (a->board)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
			if (soap_out_byte(soap, "board", -1, a->board + i, ""))
				return soap->error;
	}
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct tBlock * SOAP_FMAC4 soap_in_conecta4ns__tBlock(struct soap *soap, const char *tag, struct tBlock *a, const char *type)
{
	size_t soap_flag_code = 1;
	size_t soap_flag_msgStruct = 1;
	struct soap_blist *soap_blist_board = NULL;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct tBlock*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__tBlock, sizeof(struct tBlock), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_conecta4ns__tBlock(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_code && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_int(soap, "code", &a->code, "xsd:int"))
				{	soap_flag_code--;
					continue;
				}
			}
			if (soap_flag_msgStruct && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_conecta4ns__tMessage(soap, "msgStruct", &a->msgStruct, "conecta4ns:tMessage"))
				{	soap_flag_msgStruct--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH && !soap_element_begin_in(soap, "board", 1, NULL))
			{	if (a->board == NULL)
				{	if (soap_blist_board == NULL)
						soap_blist_board = soap_alloc_block(soap);
					a->board = (char *)soap_push_block_max(soap, soap_blist_board, sizeof(char));
					if (a->board == NULL)
						return NULL;
					soap_default_byte(soap, a->board);
				}
				soap_revert(soap);
				if (soap_in_byte(soap, "board", a->board, "xsd:byte"))
				{	a->__size++;
					a->board = NULL;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (a->board)
			soap_pop_block(soap, soap_blist_board);
		if (a->__size)
		{	a->board = (char *)soap_save_block(soap, soap_blist_board, NULL, 1);
		}
		else
		{	a->board = NULL;
			if (soap_blist_board)
				soap_end_block(soap, soap_blist_board);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_code > 0 || soap_flag_msgStruct > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
	}
	else if ((soap->mode & SOAP_XML_STRICT) && *soap->href != '#')
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	else
	{	a = (struct tBlock *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__tBlock, SOAP_TYPE_conecta4ns__tBlock, sizeof(struct tBlock), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__tBlock(struct soap *soap, const struct tBlock *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__tBlock(soap, tag ? tag : "conecta4ns:tBlock", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct tBlock * SOAP_FMAC4 soap_get_conecta4ns__tBlock(struct soap *soap, struct tBlock *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__tBlock(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_tBlock(struct soap *soap, struct tBlock *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_int(soap, &a->code);
	soap_default_conecta4ns__tMessage(soap, &a->msgStruct);
	a->__size = 0;
	a->board = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tBlock(struct soap *soap, const struct tBlock *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	soap_embedded(soap, &a->code, SOAP_TYPE_int);
	soap_serialize_conecta4ns__tMessage(soap, &a->msgStruct);
	if (a->board)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
		{
			soap_embedded(soap, a->board + i, SOAP_TYPE_byte);
		}
	}
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tBlock(struct soap *soap, const char *tag, int id, const struct tBlock *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tBlock), type))
		return soap->error;
	if (soap_out_int(soap, "code", -1, &a->code, ""))
		return soap->error;
	if (soap_out_conecta4ns__tMessage(soap, "msgStruct", -1, &a->msgStruct, ""))
		return soap->error;
	if (a->board)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
			if (soap_out_byte(soap, "board", -1, a->board + i, ""))
				return soap->error;
	}
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct tBlock * SOAP_FMAC4 soap_in_tBlock(struct soap *soap, const char *tag, struct tBlock *a, const char *type)
{
	size_t soap_flag_code = 1;
	size_t soap_flag_msgStruct = 1;
	struct soap_blist *soap_blist_board = NULL;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct tBlock*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tBlock, sizeof(struct tBlock), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_tBlock(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_code && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_int(soap, "code", &a->code, "xsd:int"))
				{	soap_flag_code--;
					continue;
				}
			}
			if (soap_flag_msgStruct && soap->error == SOAP_TAG_MISMATCH)
			{	if (soap_in_conecta4ns__tMessage(soap, "msgStruct", &a->msgStruct, "conecta4ns:tMessage"))
				{	soap_flag_msgStruct--;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH && !soap_element_begin_in(soap, "board", 1, NULL))
			{	if (a->board == NULL)
				{	if (soap_blist_board == NULL)
						soap_blist_board = soap_alloc_block(soap);
					a->board = (char *)soap_push_block_max(soap, soap_blist_board, sizeof(char));
					if (a->board == NULL)
						return NULL;
					soap_default_byte(soap, a->board);
				}
				soap_revert(soap);
				if (soap_in_byte(soap, "board", a->board, "xsd:byte"))
				{	a->__size++;
					a->board = NULL;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (a->board)
			soap_pop_block(soap, soap_blist_board);
		if (a->__size)
		{	a->board = (char *)soap_save_block(soap, soap_blist_board, NULL, 1);
		}
		else
		{	a->board = NULL;
			if (soap_blist_board)
				soap_end_block(soap, soap_blist_board);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_code > 0 || soap_flag_msgStruct > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
	}
	else if ((soap->mode & SOAP_XML_STRICT) && *soap->href != '#')
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	else
	{	a = (struct tBlock *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_tBlock, SOAP_TYPE_tBlock, sizeof(struct tBlock), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct tBlock * SOAP_FMAC4 soap_new_tBlock(struct soap *soap, int n)
{
	struct tBlock *p;
	struct tBlock *a = (struct tBlock*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct tBlock));
	for (p = a; p && n--; p++)
		soap_default_tBlock(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tBlock(struct soap *soap, const struct tBlock *a, const char *tag, const char *type)
{
	if (soap_out_tBlock(soap, tag ? tag : "tBlock", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct tBlock * SOAP_FMAC4 soap_get_tBlock(struct soap *soap, struct tBlock *p, const char *tag, const char *type)
{
	if ((p = soap_in_tBlock(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_conecta4ns__tMessage(struct soap *soap, struct tMessage *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__size = 0;
	a->msg = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_conecta4ns__tMessage(struct soap *soap, const struct tMessage *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	if (a->msg)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
		{
			soap_embedded(soap, a->msg + i, SOAP_TYPE_byte);
		}
	}
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_conecta4ns__tMessage(struct soap *soap, const char *tag, int id, const struct tMessage *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_conecta4ns__tMessage), type))
		return soap->error;
	if (a->msg)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
			if (soap_out_byte(soap, "msg", -1, a->msg + i, ""))
				return soap->error;
	}
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct tMessage * SOAP_FMAC4 soap_in_conecta4ns__tMessage(struct soap *soap, const char *tag, struct tMessage *a, const char *type)
{
	struct soap_blist *soap_blist_msg = NULL;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct tMessage*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_conecta4ns__tMessage, sizeof(struct tMessage), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_conecta4ns__tMessage(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap->error == SOAP_TAG_MISMATCH && !soap_element_begin_in(soap, "msg", 1, NULL))
			{	if (a->msg == NULL)
				{	if (soap_blist_msg == NULL)
						soap_blist_msg = soap_alloc_block(soap);
					a->msg = (char *)soap_push_block_max(soap, soap_blist_msg, sizeof(char));
					if (a->msg == NULL)
						return NULL;
					soap_default_byte(soap, a->msg);
				}
				soap_revert(soap);
				if (soap_in_byte(soap, "msg", a->msg, "xsd:byte"))
				{	a->__size++;
					a->msg = NULL;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (a->msg)
			soap_pop_block(soap, soap_blist_msg);
		if (a->__size)
		{	a->msg = (char *)soap_save_block(soap, soap_blist_msg, NULL, 1);
		}
		else
		{	a->msg = NULL;
			if (soap_blist_msg)
				soap_end_block(soap, soap_blist_msg);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct tMessage *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_conecta4ns__tMessage, SOAP_TYPE_conecta4ns__tMessage, sizeof(struct tMessage), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_conecta4ns__tMessage(struct soap *soap, const struct tMessage *a, const char *tag, const char *type)
{
	if (soap_out_conecta4ns__tMessage(soap, tag ? tag : "conecta4ns:tMessage", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct tMessage * SOAP_FMAC4 soap_get_conecta4ns__tMessage(struct soap *soap, struct tMessage *p, const char *tag, const char *type)
{
	if ((p = soap_in_conecta4ns__tMessage(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_tMessage(struct soap *soap, struct tMessage *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__size = 0;
	a->msg = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tMessage(struct soap *soap, const struct tMessage *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	if (a->msg)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
		{
			soap_embedded(soap, a->msg + i, SOAP_TYPE_byte);
		}
	}
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tMessage(struct soap *soap, const char *tag, int id, const struct tMessage *a, const char *type)
{
	(void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_tMessage), type))
		return soap->error;
	if (a->msg)
	{	int i;
		for (i = 0; i < (int)a->__size; i++)
			if (soap_out_byte(soap, "msg", -1, a->msg + i, ""))
				return soap->error;
	}
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct tMessage * SOAP_FMAC4 soap_in_tMessage(struct soap *soap, const char *tag, struct tMessage *a, const char *type)
{
	struct soap_blist *soap_blist_msg = NULL;
	if (soap_element_begin_in(soap, tag, 0, NULL))
		return NULL;
	(void)type; /* appease -Wall -Werror */
	a = (struct tMessage*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_tMessage, sizeof(struct tMessage), NULL, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_tMessage(soap, a);
	if (soap->body && *soap->href != '#')
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap->error == SOAP_TAG_MISMATCH && !soap_element_begin_in(soap, "msg", 1, NULL))
			{	if (a->msg == NULL)
				{	if (soap_blist_msg == NULL)
						soap_blist_msg = soap_alloc_block(soap);
					a->msg = (char *)soap_push_block_max(soap, soap_blist_msg, sizeof(char));
					if (a->msg == NULL)
						return NULL;
					soap_default_byte(soap, a->msg);
				}
				soap_revert(soap);
				if (soap_in_byte(soap, "msg", a->msg, "xsd:byte"))
				{	a->__size++;
					a->msg = NULL;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (a->msg)
			soap_pop_block(soap, soap_blist_msg);
		if (a->__size)
		{	a->msg = (char *)soap_save_block(soap, soap_blist_msg, NULL, 1);
		}
		else
		{	a->msg = NULL;
			if (soap_blist_msg)
				soap_end_block(soap, soap_blist_msg);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct tMessage *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_tMessage, SOAP_TYPE_tMessage, sizeof(struct tMessage), 0, NULL, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 struct tMessage * SOAP_FMAC4 soap_new_tMessage(struct soap *soap, int n)
{
	struct tMessage *p;
	struct tMessage *a = (struct tMessage*)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(struct tMessage));
	for (p = a; p && n--; p++)
		soap_default_tMessage(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tMessage(struct soap *soap, const struct tMessage *a, const char *tag, const char *type)
{
	if (soap_out_tMessage(soap, tag ? tag : "tMessage", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct tMessage * SOAP_FMAC4 soap_get_tMessage(struct soap *soap, struct tMessage *p, const char *tag, const char *type)
{
	if ((p = soap_in_tMessage(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Reason))
		soap_serialize_SOAP_ENV__Reason(soap, *a);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Reason *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Reason, NULL);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Reason(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap *soap, const char *tag, struct SOAP_ENV__Reason **a, const char *type)
{
	(void)type; /* appease -Wall -Werror */
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Reason **)soap_malloc(soap, sizeof(struct SOAP_ENV__Reason *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Reason(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Reason **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *const*a, const char *tag, const char *type)
{
	if (soap_out_PointerToSOAP_ENV__Reason(soap, tag ? tag : "SOAP-ENV:Reason", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Reason(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Detail))
		soap_serialize_SOAP_ENV__Detail(soap, *a);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Detail *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Detail, NULL);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Detail(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap *soap, const char *tag, struct SOAP_ENV__Detail **a, const char *type)
{
	(void)type; /* appease -Wall -Werror */
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Detail **)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Detail(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Detail **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *const*a, const char *tag, const char *type)
{
	if (soap_out_PointerToSOAP_ENV__Detail(soap, tag ? tag : "SOAP-ENV:Detail", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Detail(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Code))
		soap_serialize_SOAP_ENV__Code(soap, *a);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Code *const*a, const char *type)
{
	char *mark;
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Code, &mark);
	if (id < 0)
		return soap->error;
	(void)soap_out_SOAP_ENV__Code(soap, tag, id, *a, type);
	soap_unmark(soap, mark);
	return soap->error;
}

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code **a, const char *type)
{
	(void)type; /* appease -Wall -Werror */
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Code **)soap_malloc(soap, sizeof(struct SOAP_ENV__Code *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Code(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Code **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a, const char *tag, const char *type)
{
	if (soap_out_PointerToSOAP_ENV__Code(soap, tag ? tag : "SOAP-ENV:Code", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Code(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToconecta4ns__tBlock(struct soap *soap, struct tBlock *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	if (!soap_reference(soap, *a, SOAP_TYPE_conecta4ns__tBlock))
		soap_serialize_conecta4ns__tBlock(soap, *a);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToconecta4ns__tBlock(struct soap *soap, const char *tag, int id, struct tBlock *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_conecta4ns__tBlock, NULL);
	if (id < 0)
		return soap->error;
	return soap_out_conecta4ns__tBlock(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct tBlock ** SOAP_FMAC4 soap_in_PointerToconecta4ns__tBlock(struct soap *soap, const char *tag, struct tBlock **a, const char *type)
{
	(void)type; /* appease -Wall -Werror */
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct tBlock **)soap_malloc(soap, sizeof(struct tBlock *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_conecta4ns__tBlock(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct tBlock **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_conecta4ns__tBlock, sizeof(struct tBlock), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToconecta4ns__tBlock(struct soap *soap, struct tBlock *const*a, const char *tag, const char *type)
{
	if (soap_out_PointerToconecta4ns__tBlock(soap, tag ? tag : "conecta4ns:tBlock", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct tBlock ** SOAP_FMAC4 soap_get_PointerToconecta4ns__tBlock(struct soap *soap, struct tBlock **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToconecta4ns__tBlock(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap *soap, int *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	(void)soap_reference(soap, *a, SOAP_TYPE_int);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap *soap, const char *tag, int id, int *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_int, NULL);
	if (id < 0)
		return soap->error;
	return soap_out_int(soap, tag, id, *a, type);
}

SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap *soap, const char *tag, int **a, const char *type)
{
	(void)type; /* appease -Wall -Werror */
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (int **)soap_malloc(soap, sizeof(int *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_int(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (int **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_int, sizeof(int), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap *soap, int *const*a, const char *tag, const char *type)
{
	if (soap_out_PointerToint(soap, tag ? tag : "int", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap *soap, int **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToint(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap *soap, char *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	(void)soap_reference(soap, *a, SOAP_TYPE_xsd__string);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_xsd__string);
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap *soap, const char *tag, char **a, const char *type)
{
	a = soap_instring(soap, tag, a, type, SOAP_TYPE_xsd__string, 1, 0, -1, NULL);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	if (soap_out_xsd__string(soap, tag ? tag : "xsd:string", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in_xsd__string(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap *soap, char *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	(void)soap_reference(soap, *a, SOAP_TYPE__QName);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE__QName);
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap *soap, const char *tag, char **a, const char *type)
{
	a = soap_instring(soap, tag, a, type, SOAP_TYPE__QName, 2, 0, -1, NULL);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	if (soap_out__QName(soap, tag ? tag : "QName", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in__QName(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap *soap, char *const*a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
#ifndef WITH_NOIDREF
	(void)soap_reference(soap, *a, SOAP_TYPE_string);
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_string);
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap *soap, const char *tag, char **a, const char *type)
{
	a = soap_instring(soap, tag, a, type, SOAP_TYPE_string, 1, 0, -1, NULL);
	return a;
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_new_string(struct soap *soap, int n)
{
	char * *p;
	char * *a = (char **)soap_malloc((soap), (n = (n < 0 ? 1 : n)) * sizeof(char *));
	for (p = a; p && n--; p++)
		soap_default_string(soap, p);
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	if (soap_out_string(soap, tag ? tag : "string", -2, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in_string(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapC.c */
